<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Polly" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Azure.Cosmos" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CalmClass.Application\CalmClass.Application.csproj" />
    </ItemGroup>

</Project>
