config:
  azure-native:location: westeurope
  CalmClass.IaC:environment: prod
  CalmClass.IaC:resourcePrefix: calmclass-prod
  CalmClass.IaC:cosmosDatabaseName: CalmClassDb
  CalmClass.IaC:cosmosContainerName: Polls
  CalmClass.IaC:quietHoursStartHour: "20"
  CalmClass.IaC:quietHoursEndHour: "8"
  CalmClass.IaC:quietHoursTimeZoneId: Europe/Kyiv
  CalmClass.IaC:telegramBotToken: "placeholder-prod-token"
  CalmClass.IaC:telegramSecretToken: "placeholder-prod-secret"
