<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="testconfig.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\CalmClass.Application\CalmClass.Application.csproj" />
        <ProjectReference Include="..\..\..\src\CalmClass.Infrastructure\CalmClass.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="Microsoft.Testing.Platform" />
        <PackageReference Include="Moq" />
        <PackageReference Include="TUnit" />
    </ItemGroup>
</Project>
